name: projecthit
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  outline_material_icons: ^0.1.1
  provider: ^5.0.0
  intl: ^0.17.0
  package_info: ^2.0.0
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.1
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^9.1.0
  english_words: ^4.0.0
  share: ^2.0.1
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  cached_network_image: ^3.0.0
  implicitly_animated_reorderable_list: ^0.3.2
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
