name: projecthit
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  outline_material_icons: ^0.1.1
  provider: ^4.3.3
  intl: ^0.16.1
  package_info: ^0.4.3+4
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  firebase_dynamic_links: ^0.7.0+1
  firebase_messaging: ^8.0.0-dev.15
  english_words: ^3.1.5
  share: ^0.6.5+4
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
